name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  PushReadmeJob:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: davidelanz
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: davidelanz/paddle-ocr
          provider: dockerhub
          short_description: "Dockerfile for PaddleOCR >= 2.0.6"
          readme_file: "README.md"

  BuildPushImagesJob:
    runs-on: ubuntu-latest
    name: Build and push images to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: CPU
        env:
          DOCKER_USER: davidelanz
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
          && docker build . --file docker/cpu --tag davidelanz/paddle-ocr:cpu
          && docker push davidelanz/paddle-ocr:cpu

      - name: GPU [CUDA 10.0, CUDNN 7]
        env:
          DOCKER_USER: davidelanz
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
          && docker build . --file docker/cuda10.0-cudnn7-devel --tag davidelanz/paddle-ocr:gpu-cuda10.0-cudnn7-devel
          && docker push davidelanz/paddle-ocr:gpu-cuda10.0-cudnn7-devel

      - name: GPU [CUDA 10.1, CUDNN 7]
        env:
          DOCKER_USER: davidelanz
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
          && docker build . --file docker/cuda10.1-cudnn7-devel --tag davidelanz/paddle-ocr:gpu-cuda10.1-cudnn7-devel
          && docker push davidelanz/paddle-ocr:gpu-cuda10.1-cudnn7-devel

      - name: GPU [CUDA 11.0, CUDNN 8]
        env:
          DOCKER_USER: davidelanz
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
          && docker build . --file docker/cuda11.0-cudnn8-devel --tag davidelanz/paddle-ocr:gpu-cuda11.0-cudnn8-devel
          && docker push davidelanz/paddle-ocr:gpu-cuda11.0-cudnn8-devel
