name: Docker Image CI

on: 
  push:
    branches: [main] 

jobs:

  build:
  
    runs-on: ubuntu-latest   
    
    steps:
      - uses: actions/checkout@v2
      - name: Login to docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run:
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the docker image
        run: cd docker && docker build . --file Dockerfile --tag davidelanz/paddle-ocr:latest
      - name: Push Image to hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/paddle-ocr
      - name: Push README to hub        
        run: docker pushrm ${{ secrets.DOCKER_USERNAME }}/paddle-ocr
