name: Docker Image CI

on: 
  push:
    branches: [main] 
    
jobs:
  PushContainerReadme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: $DOCKER_USERNAME/paddle-ocr
          provider: dockerhub
          short_description: 'Dockerfile for PaddleOCR >= 2.0.6'
          readme_file: 'README.md'
        
  build-cpu:
    runs-on: ubuntu-latest
    name: Build CPU Image
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Image to Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run:
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          && cd docker && docker build . --file python3 --tag davidelanz/paddle-ocr:cpu
          && docker push $DOCKER_USERNAME/paddle-ocr
        
  build-gpu-cuda10_1-cudnn7:
    runs-on: ubuntu-latest
    name: Build GPU cuda10.1 cudnn7 Image
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Image to Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run:
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          && cd docker && docker build . --file pytorch:1.6.0-cuda10.1-cudnn7-devel --tag davidelanz/paddle-ocr:gpu-cuda10.1-cudnn7
          && docker push $DOCKER_USERNAME/paddle-ocr
