name: Docker Image CI

on: 
  push:
    branches: [ master] 

jobs:

  build:
  
    runs-on: ubuntu-latest   
    
    steps:
      - uses: actions/checkout@v2
      - name: Login to docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run:
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the docker image
        run: docker build . --file Dockerfile --tag davidelanz/paddle-ocr:$(date + %s)
      - name: Push to hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/paddle-ocr
