name: Docker Image CI

on: 
  push:
    branches: [main] 
    
jobs:
  PushContainerReadme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: my-user
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: ${{ secrets.DOCKER_USERNAME }}/paddle-ocr
          provider: dockerhub
          short_description: 'Dockerfile for PaddleOCR >= 2.0.6'
          readme_file: 'README.md'
        
  build-cpu:
    runs-on: ubuntu-latest
    name: Build CPU Image
    steps:
      - uses: actions/checkout@v2
      - name: Login to Dockerhub
        run:
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker Image
        run: cd docker && docker build . --file python3 --tag davidelanz/paddle-ocr:cpu
      - name: Push Image to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/paddle-ocr
        
  build-gpu-cuda10.1-cudnn7:
    runs-on: ubuntu-latest
    name: Build GPU cuda10.1 cudnn7 Image
    steps:
      - uses: actions/checkout@v2
      - name: Login to Dockerhub
        run:
          docker login ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker Image
        run: cd docker && docker build . --file pytorch:1.6.0-cuda10.1-cudnn7-devel --tag davidelanz/paddle-ocr:gpu-cuda10.1-cudnn7
      - name: Push Image to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/paddle-ocr

